services:

  app-dev:
    container_name: app-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./src:/app/src
    depends_on:
      - auth-db
      - auth-redis

  auth-db:
    container_name: auth-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=authdb

  auth-redis:
    container_name: auth-redis
    image: redis:7.2 # Usamos la imagen oficial de Redis
    restart: always
    volumes:
      - redis_data:/data # Persistimos los datos de Redis
    command: redis-server --appendonly yes # Habilitamos persistencia
    ports:
      - "6379:6379"

volumes:
  redis_data: # Definimos el volumen para Redis